# Generated by Django 4.0.5 on 2022-06-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackListedToken',
        ),
    ]
