# Generated by Django 4.0.5 on 2022-06-21 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_skillsmodel_userinformations_experiencemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
