# Generated by Django 4.0.5 on 2022-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_userinformations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencemodel',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
